version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ruby_user
      POSTGRES_PASSWORD: ruby_pass
      POSTGRES_DB: ruby_app_dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  ruby_ddd:
    build: .
    depends_on:
      - db
    ports:
      - '4567:4567'
    volumes:
      - .:/app
      - /app/vendor/bundle
    environment:
      RACK_ENV: development
      DATABASE_URL: postgres://ruby_user:ruby_pass@db:5432/ruby_app_dev

volumes:
  pgdata:
