version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ruby_app_dev
    ports:
      - '5432:5432'
    networks:
      - postgres

  ruby_ddd:
    build: .
    container_name: ruby_ddd
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ruby_app_dev
    depends_on:
      - db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
